server:
  port: 9005
  http2:
    enabled: true
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  forward-headers-strategy: framework

spring:

  r2dbc:
    url: r2dbc:postgresql://localhost:5433/iozone
    username: iozone
    password: iozone
    pool:
      enabled: true
      max-life-time: PT30M # 15 minutes
      validation-query: select 1;

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:31380/auth/realms/iozone
          jwk-set-uri: http://localhost:31380/auth/realms/iozone/protocol/openid-connect/certs


management:
  endpoint:
    metrics:
      enabled: true

springdoc:
  oauth-flow:
    authorization-url: http://localhost:31380/auth/realms/iozone/protocol/openid-connect/auth
    token-url: http://localhost:31380/auth/realms/iozone/protocol/openid-connect/token
    scopes:
      openid: openid scope
      profile: connected user profile scope
      email: connected user email scope
      iozone.backlog.write: Backlog update & creation scope
      iozone.backlog.read: Backlog view scope
      iozone.backlog.mgnt: Backlog management (read + write) scope

logging:
  level:
    root: INFO
